# Generated by Django 4.1.7 on 2023-03-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_location_user_location"),
        ("ads", "0002_alter_ad_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
