# Generated by Django 4.1.7 on 2023-04-02 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_description_alter_ad_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
